PiUpld/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Upld.urls')),
]

Upld/urls.py
from django.urls import path
from . import views

app_name = "Upld"

urlpatterns = [
path('', views.IndexView.as_view(), name = 'index'),
path('ProjectCreateView', views.ProjectCreateView.as_view(), name='ProjectCreateView'),
path('ClassStream', views.StreamingTest.as_view(), name = 'ClassStream'),
]

Upld/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

from os.path import join
from .git_interface import clone_repo, delete_project
from .managers import BulkQueryManager


UPLOADS_PATH = join(settings.MEDIA_ROOT, "uploads")

class GitHubProject(models.Model):
    uploaded = models.DateTimeField(auto_now_add = True)
    last_modified = models.DateTimeField(auto_now = True)
    git_link = models.URLField(max_length = 300)
    name = models.SlugField(max_length = 100)
    local_git_repo = models.FilePathField(allow_folders=True, default=UPLOADS_PATH)

    objects = BulkQueryManager()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.name = self.git_link.split("/")[-1].split(".")[0]
            self.local_git_repo = join( UPLOADS_PATH, self.name)
            git_hub_repo = clone_repo(self.git_link, self.local_git_repo)
        print(self.local_git_repo)
        super(GitHubProject, self).save(*args, **kwargs)
        print(self.local_git_repo)


    def delete(self):
        delete_project(self.local_git_repo)
        super().delete()

Upld/forms.py
from django import forms
from .git_interface import validate_git_url
from .models import GitHubProject

class NewProjectForm(forms.ModelForm):
    class Meta:
        model = GitHubProject
        fields = ['git_link',]

    def clean_git_link(self):
        data = self.cleaned_data['git_link']
        if validate_git_url(data):
            return data
        else:
            raise forms.ValidationError("Invalid Git repository!", code='invalid')

Upld/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import GitHubProject
from .forms import *
from .platformio_interface import *

class IndexView(generic.ListView):
    template_name = "Upld/index.html"
    model = GitHubProject

    def get_context_data(self, **kwargs):
        ''' added available devices to context'''
        context = super().get_context_data(**kwargs)
        context['devices'] = get_devices()
        print(context)
        context['streamed'] = StreamingHttpResponse(WriteToDevice()).streaming_content
        return context

    def get_queryset(self):
        ''' return a list of all projects'''
        print(GitHubProject.objects.all())
        return GitHubProject.objects.all()


class ProjectCreateView(generic.edit.CreateView):
    form_class = NewProjectForm
    model = GitHubProject
    template_name = "Upld/ProjectCreate.html"
    success_url = reverse_lazy("Upld:index")




from django.http import StreamingHttpResponse
import subprocess

class iteratorTest():
    def __init__(self):
        pass
    def __iter__(self):
        self.proc = subprocess.Popen(["ping", "192.168.0.5", "-t"],
                                    stdout=subprocess.PIPE,
                                    shell=True,
                                    universal_newlines = True,
                                    bufsize=1)
        return self
    def __next__(self):
        for line in self.proc.stdout:
            return "<br>" + line



class StreamingTest(generic.ListView):
    template_name = 'Upld/StreamingTest.html'
    def get_queryset(self, **kwargs):
        return None

    def dispatch(self, request, *args, **kwargs):
        if request.method.lower() == 'get':
            response = StreamingHttpResponse(WriteToDevice())
            return response
        else:
            return super(StreamingTest, self).dispatch(request, *args, **kwargs)

Upld/templates/Upld/ProjectCreate.html
{% extends 'Upld/base.html' %}
{% block content %}


<div class = "main_window">

<div class = "container">
  <div class = "container_title">
  Create New Project
  </div>

{% if form.valid %}
<a href = "{% url 'Upld:index' %}">
  <div class = "container_content">

    <ul>
   Successfully created new project!
   </ul

  </div>
  </a>
</div>
{% else %}
<div class = "container_content">

  {{ form.as_table }}

<input type="submit" value="Add Project"></input>
</div>
{% endif %}


{% endblock content %}

Upld/templates/Upld/StreamingTest.html
{% extends 'Upld/base.html' %}
{% block content %}


<div class = "main_window">

<div class = "container">
  <div class = "container_title">
  Container 1
  </div>

  <div class = "container_content">

    {{ test }}

  </div>
</div>




<div class = "container">
  <div class = "container_title">
  Container 2
  </div>

  <div class = "container_content">

  </div>
</div>

<div class = "container">
  <div class = "container_title">
  Container 3
  </div>
  <div class = "container_content">


  </div>
</div>


</div>



{% endblock content %}

Upld/templates/Upld/base.html
<html>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Upld/style.css' %}"></link>
<script src="{% static 'Upld/JS_Library.js' %}"></script>

<body>
<div class = "top_bar">
  <a href = "{% url 'Upld:index' %}">
    <h2> PiUpld </h2>
  </a>
</div>

<div class = "main_content">
{% block content %}
{% endblock content %}
</div>
</body>
</html>

Upld/templates/Upld/index.html
{% extends 'Upld/base.html' %}
{% block content %}


<div class = "main_window">

<div class = "container">
  <div class = "container_title">
  Boards
  </div>

  <div class = "container_content">
  {% for device in devices %}
    <div id="device['Hardware ID']">
      {% for key, item in device.items %}
          <div class=DeSelected id="{{ key }}"> {{ key }}: {{ item }}</div>
          <br>
      {% endfor%}
    </div>
  {% empty %}
      <div>
        <div> Error: No Devices Found </div>
      </div>
  {% endfor %}
  </div>
</div>

{% if devices %}
<script type="text/javascript">
  setupSelection("Boards", [{% for device in devices %} "{{ device.port }}", {% endfor %}]);
</script>
{% endif %}


<div class = "container">
  <div class = "container_title">
  Project
  </div>

  <div class = "container_content">
    <ul>
   {% for project in githubproject_list %}

        <div class=DeSelected id="project_{{ project.name }}"> {{ project.name }} </div>
  {% empty %}
        <div> Error: No Projects Found </div>
   {% endfor %}
   </ul>

   {% if githubproject_list %}
   <script type="text/javascript">
     setupSelection("Projects", [{% for project in githubproject_list %} "project_{{ project.name }}", {% endfor %}]);
   </script>
   {% endif %}

   <button onclick="hideOrUnhide('addproject_modal', 'block')"> Add Project </button>
  </div>
</div>

<div class = "container">
  <div class = "container_title">
  Stuff3
  </div>
  <div class = "container_content">

    <div class=DeSelected id="Selectable_1"> Item 1 </div>
    <div class=DeSelected id="Selectable_2"> Item 2 </div>
  </div>
</div>
<script type="text/javascript">
  setupSelection("Test Selection", ["Selectable_1", "Selectable_2"]);
</script>


<div class = "container">
  <div class = "container_title">
  Stuff3
  </div>
  <div class = "container_content">
    <form method = "get" action="{% url 'Upld:ClassStream' %}">
      {% csrf_token %}
      <input type="submit"> run terminal </input>
      </form>

  </div>
</div>

<div class = "container">
  <div class = "container_title">
  Stuff3
  </div>
  <div class = "container_content" style="padding:0;">

    <iframe src = "{% url 'Upld:ClassStream' %}" class= "Terminal_iframe" id="Terminal_iframe1">
      </iframe>


  </div>
</div>
<script type="text/javascript">
  window.setInterval( reloadiFrame('Terminal_iframe1') , 3000);
</script>

</div>

<div class = "modal_overlay"
      id="addproject_modal"
      onclick="hideOrUnhide('addproject_modal', 'block')"
      style:"display:none;">
<div class="modal_box" onclick= "event.stopPropagation();">
  <form method = "post" action="{% url 'Upld:ProjectCreateView' %}">
    {% csrf_token %}
    <input name = "git_link" type="text" id ="id_git_link"></input>
    <input type="submit" value="Add Project"></input>
  </form>
 </div>
</div>


{% endblock content %}